services:
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/tmp/nginx.conf
    environment: 
      - FLASK_SERVER_ADDR=backend:9091
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 8080:8080
    depends_on:
      - backend

  backend:
    build:
      context: .
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    environment:
      - GUNICORN_CMD_ARGS=--bind=0.0.0.0:9091
      - MONGODB_URI=${MONGODB_URI}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - FETCH_PASSWORD=${FETCH_PASSWORD}
      - DATABASE_PATH=${DATABASE_PATH}
      - CFD_DATASET_PATH=${CFD_DATASET_PATH}
    volumes:
      - ./:/app
    depends_on:
      -  mongo  

  mongo:
    image: mongo
    volumes:
      - mongo_vol:/data/db

volumes:
  mongo_vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${DATABASE_PATH}'
  cfd_dataset:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${CFD_DATASET_PATH}'
